#!/bin/bash
#
# Script to perform some common system operations
#

shopt -s expand_aliases
source ~/.bash_aliases

echo "Loading please wait...."
red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 6`
reset=`tput sgr0`
cd ~/GitRepo
export raspi1="192.168.0.200" 
export raspi2="192.168.1.2" 
export raspi3="192.168.1.3" 
export raspi4="192.168.1.4" 
export raspi5="192.168.1.5" 
export raspi6="192.168.0.130"
export raspi7="192.168.0.131"
export raspiD="192.168.0.111" 
export server="192.168.0.110" 
export server_mac="F0:4D:A2:DB:E0:D8"
declare ip_address=("$raspi1" "$raspi2" "$raspi3" "$raspi4" "$raspi5" "$raspi6" "$raspi7" "$raspiD" "$server")
for i in "${ip_address[@]}"
do
  case $i in
	192.168.0.200)
		name=Raspi1
		;;
	192.168.1.2)
		name=Raspi2
		;;
	192.168.1.3)
		name=Raspi3
		;;
	192.168.1.4)
		name=Raspi4
		;;
	192.168.1.5)
		name=Raspi5
		;;
	192.168.0.130)
		name=Raspi6
		;;
	192.168.0.131)
		name=Raspi7
		;;
	192.168.0.111)
		name=RaspiD
		;;
	192.168.0.110)
		name=Server
		;;
	esac
  if ping -c 1 -W 1 $i > /dev/null; then
	export ${name}_ifup="On-Line"
  else
    export ${name}_ifup="Off-Line"
  fi
done
export my_ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
export PUBLIC_IP=$my_ip
export internal_ip=$(hostname -I)
export iaincstott_ip=$(dig +short iaincstott.co.uk @resolver1.opendns.com)
export domain_ip=$iaincstott_ip
website_up=$(./Scripts/backend/website_ifup)
uptime=$(  uptime | tr "," " " | cut -f4-5 -d" ")
df_websites=$(ssh root@192.168.0.200 df -H /mnt/Backup /mnt/Storage /mnt/Websites /)
if [ $domain_ip == $PUBLIC_IP ]; then 
	export DOMAIN_IP="${green}$domain_ip${reset}"
else
	export DOMAIN_IP="${red}$domain_ip${reset}"
fi
if [ $domain_ip == $PUBLIC_IP ]; then 
	export public_ip="${green}$PUBLIC_IP${reset}"
else
	export public_ip="${red}$PUBLIC_IP${reset}"
fi
while :
do
clear
echo "******************************************************************"
echo "* ${blue}Systems Menu${reset} *				${blue}RPi 1 = ${reset}$Raspi1_ifup "
echo "* ${blue}Domain IP = ${reset}$DOMAIN_IP *				${blue}RPi 2 = ${reset}$Raspi2_ifup"
echo "* ${blue}Public IP = ${reset}$public_ip *			${blue}RPi 3 = ${reset}$Raspi3_ifup" 
echo "* ${blue}Laptop IP = ${reset}${green}$internal_ip${reset} *			${blue}RPi 4 = ${reset}$Raspi4_ifup"
echo "* ${blue}Website = ${reset}$website_up *				${blue}RPi 5 = ${reset}$Raspi5_ifup"
echo "* ${blue}Uptime = ${reset}$uptime 				${blue}RPi 6 = ${reset}$Raspi6_ifup"
echo "* ${blue}OS = ${reset}"$(cat /etc/issue.net)"                    ${blue}Server = ${reset}$Server_ifup"
echo "* ${blue}Remote Storage -${green} 
$df_websites${reset}"
echo "******************************************************************"
echo "* [1] SSH Menu"
echo "* [2] Run Remote App"
echo "* [3] Kodi Tools"
echo "* [4] Development Tools"
echo "* [5] Flash SD/USB "
echo "* [6] Servers Menu"
echo "* [7] Kill App"
echo "* [8] Sleep Server"
echo "* [9] Wake Server"
echo "* "
echo "* [u] Update Git Repos"
echo "* [r] Reload Menu"
echo "* [x] Exit/Stop *"
echo "******************************************************************"
echo "Enter your menu choice [1-0]: "
read yourch
case $yourch in
1) osascript ./Mac\ Scripts/002\ -\ SSH\ Connect.scpt ;;
2) nemo sftp://$USER@192.168.0.4/media/Software/Downloads/ ;;
3) ./Scripts/backend ;;
4) ssh -X $USER@192.168.0.4 pyrenamer ;;
5) /home/iainstott/.bin/ddusb & ;;
6)  ;;
7)  ;;
8) ssh iainstott@${server} sudo pm-hibernate ;;
9) wakeonlan $server_mac ;;
u) cd /home/iainstott/GitRepo/ && for i in $( ls ); do cd $i; echo "Repository = "$i; git-update; echo ""; cd /home/iainstott/GitRepo; done ;;
s) sh ./Scripts/backend/secret.script ;;
r) sh ./Scripts/Menu ;;
s2) sh ./Scripts/backend/secret2.script ;;
x) exit 0;;
*) echo "Oopps!!! Please select choice 1,2,3 or 4";
echo "Press Enter to continue. . ." ; read ;;
esac
done
