#!/bin/bash
#
# Script to perform some common system operations
#
red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 6`
reset=`tput sgr0`
cd ~/OneDrive/Dev/
export rpi1_ip="192.168.0.200" 
export rpi2_ip="192.168.1.2" 
export rpi3_ip="192.168.1.3" 
export rpi4_ip="192.168.1.4" 
export rpi5_ip="192.168.1.5" 
export rpi6_ip="192.168.0.129" 
export server_ip="192.168.0.110" 
rpi1_ifup=$(export machine=$rpi1_ip && ./Scripts/backend/ifup)
rpi2_ifup=$(export machine=$rpi2_ip && ./Scripts/backend/ifup)
rpi3_ifup=$(export machine=$rpi3_ip && ./Scripts/backend/ifup)
rpi4_ifup=$(export machine=$rpi4_ip && ./Scripts/backend/ifup)
rpi5_ifup=$(export machine=$rpi5_ip && ./Scripts/backend/ifup)
rpi6_ifup=$(export machine=$rpi6_ip && ./Scripts/backend/ifup)
server_ifup=$(export machine=$server_ip && ./Scripts/backend/ifup)
export my_ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
export PUBLIC_IP=$my_ip
export internal_ip=$(ipconfig getifaddr en0)
export iaincstott_ip=$(dig +short iaincstott.co.uk @resolver1.opendns.com)
export domain_ip=$iaincstott_ip
website_up=$(./Scripts/backend/website_ifup)
uptime=$(  uptime | tr "," " " | cut -f4-5 -d" ")
os=$(sw_vers -productVersion)
df_websites=$(ssh root@192.168.0.200 df -H /mnt/Backup /mnt/Storage /mnt/Websites /)
if [ $domain_ip == $PUBLIC_IP ]; then 
	export DOMAIN_IP="${green}$domain_ip${reset}"
else
	export DOMAIN_IP="${red}$domain_ip${reset}"
fi
if [ $domain_ip == $PUBLIC_IP ]; then 
	export public_ip="${green}$PUBLIC_IP${reset}"
else
	export public_ip="${red}$PUBLIC_IP${reset}"
fi
if [ $os == 10.10 ]; then
	OS="Yosemite"
elif [ $os == 10.11 ]; then
	OS="El Capitan"
fi
while :
do
clear
echo "****************************************************************************************************"
echo "* ${blue}Systems Menu${reset} *				${blue}RPi 1 = ${reset}$rpi1_ifup "
echo "* ${blue}Domain IP = ${reset}$DOMAIN_IP *			${blue}RPi 2 = ${reset}$rpi2_ifup"
echo "* ${blue}Public IP = ${reset}$public_ip *			${blue}RPi 3 = ${reset}$rpi3_ifup" 
echo "* ${blue}Laptop IP = ${reset}${green}$internal_ip${reset} *			${blue}RPi 4 = ${reset}$rpi4_ifup"
echo "* ${blue}Website = ${reset}$website_up *				${blue}RPi 5 = ${reset}$rpi5_ifup"
echo "* ${blue}Uptime = ${reset}$uptime 				${blue}RPi 6 = ${reset}$rpi6_ifup"
echo "* ${blue}OS = ${reset}OS X $os - $OS		       ${blue}Server = ${reset}$server_ifup"
echo "* ${blue}Remote Storage -${green} 
$df_websites${reset}"
echo "****************************************************************************************************"
echo "* [1] SSH Menu"
echo "* [2] Run Remote App"
echo "* [3] Kodi Tools"
echo "* [4] Development Tools"
echo "* [5] Flash SD/USB "
echo "* [6] Servers Menu"
echo "* [7] Restart Servers"
echo "* [8] Sleep Server"
echo "* [9] Wake Server"
echo ""
echo "* [r] Reload Menu"
echo "* [x] Exit/Stop *"
echo "****************************************************************************************************"
echo "Enter your menu choice [1-0]: "
read yourch
case $yourch in
1) osascript ./Mac\ Scripts/002\ -\ SSH\ Connect.scpt ;;
2) nemo sftp://$USER@192.168.0.4/media/Software/Downloads/ ;;
3) ssh -X $USER@192.168.0.4 sh /home/iainstott/scripts/sorttv.script ;;
4) ssh -X $USER@192.168.0.4 pyrenamer ;;
5) gnome-terminal -e "ssh $USER@192.168.0.4 screen -r" ;;
6)  ;;
7)  ;;
8) osascript ./Mac\ Scripts/ssh_connect.scpt ;;
9) sh ./Scripts/backend/updateip ;;
s) sh ./Scripts/backend/secret.script ;;
r) sh ./Scripts/Menu ;;
s2) sh ./Scripts/backend/secret2.script ;;
x) exit 0;;
*) echo "Oopps!!! Please select choice 1,2,3 or 4";
echo "Press Enter to continue. . ." ; read ;;
esac
done
