#!/bin/bash
reset
echo "Copying TV Config To Backup....."
rsync -a "/Users/iainstott/Library/Application Support/Kodi/userdata/addon_data/script.ftvguide" "/Users/iainstott/Desktop/Kodi/TV Config/userdata/addon_data"
cd "/Users/iainstott/Desktop/Kodi/TV Config/"
echo "Creating Archive....."
rm -rf ../tv_guide_settings.zip
zip -r /Users/iainstott/Desktop/Kodi/tv_guide_settings.zip "./userdata" > /dev/null
echo "Copying Archive To Server....."
sshpass -p '3L3phunk84%' rsync --progress /Users/iainstott/Desktop/Kodi/tv_guide_settings.zip root@192.168.0.200:/var/www/iaincstott.co.uk/kodirepo
sshpass -p '3L3phunk84%' ssh root@192.168.0.200 'chmod 777 /var/www/iaincstott.co.uk/kodirepo/tv_guide_settings.zip'
sshpass -p '3L3phunk84%' ssh root@192.168.0.200 'chown 1000:1000 /var/www/iaincstott.co.uk/kodirepo/tv_guide_settings.zip'
osascript -e 'display notification "Kodi Config Creation Complete" with title "Done"'
