#!/bin/bash
cd ~/Library/Application\ Support/Kodi/userdata/addon_data/script.renegadestv/
curl -O https://raw.githubusercontent.com/RenegadesTV/repository.renegadestv/master/addons2.ini
rm -rf ./links.txt && rm -rf ./links2.txt
grep -Ei "=" ./addons2.ini >> ./links.txt 
rm -rf ./channels.m3u
echo "#EXTM3U" > ./channels.m3u
