#!/bin/bash
cd ~/Library/Application\ Support/Kodi/userdata/addon_data/script.renegadestv/


name=$( cat ./name.txt )
name2=${name:1:${#name}-2}
url=$( cat ./url.txt )
url2=${url:1:${#url}-2}
url3=${url2%??}
check=${#url3}

if grep -qi daffy <<<$url2; then
	check="0"
fi

if grep -qi israelive <<<$url2; then
	check="0"
fi

if grep -qi albania <<<$name; then
	check="0"
fi
if grep -qi czech <<<$name; then
	check="0"
fi

if grep -qi afrika <<<$name; then
	check="0"
fi

if grep -qi mdfubar <<<$url2; then
	check="0"
fi

if grep -qi plugin <<<$name; then
	check="0"
fi

if [ $check == 0 ]; then
	exit;
else	
	echo "#EXTINF:-1, $name2" >> ./channels.m3u
	echo "$url3" >> ./channels.m3u
fi
