#!/bin/bash
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
exec 3>/dev/tcp/${machine}/22
if [ $? -eq 0 ]
then
    status=UP
else
    status=DOWN
fi
if [ $status = UP ]
then 
	echo "${green}Online${reset}"
else
	echo "${red}Offline${reset}"
fi