#!/bin/bash
#!/bin/sh
storage_dir=/media/Data_Drive/ISO_Images

plop=${storage_dir}/plop.iso
mintx32=${storage_dir}/mintx32.iso
mintx64=${storage_dir}/mintx64.iso
debian8x32net=${storage_dir}/debian8x32net.iso
debian8x64net=${storage_dir}/debian8x64net.iso
centos7=${storage_dir}/centos7.iso
centos7net=${storage_dir}/centos7net.iso
ubuntu1604x32=${storage_dir}/ubuntu16.04x32.iso
ubuntu1604x64=${storage_dir}/ubuntu16.04x64.iso
raspbian_jessie=${storage_dir}/raspbian_jessie.img
raspbian_wheezy=${storage_dir}/raspbian_wheezy.img
bananian=${storage_dir}/bananian.img
openelec=${storage_dir}/openelec.img
serverR2=${storage_dir}/2012R2.iso
sevenx32="${storage_dir}/7x32.iso"
sevenx64="${storage_dir}/7x64.iso"
tenx32="${storage_dir}/10x32.iso"
tenx64="${storage_dir}/10x64.iso"

NULL=/dev/null

ANS1=$(zenity  --list  --text "Type Of Installation" --radiolist  --column "Pick" --column "Type" TRUE "USB and SD Memory" FALSE "CD and DVD Disc")

case "$ANS1" in
	"USB and SD Memory")
		driveinfo=$(sudo lsblk -io KNAME,TYPE,SIZE,MODEL)
		zenity --info --width=600 --title="Drive Info" --text="${driveinfo}" 
		DRIVE=$(find /dev -mindepth 1 -maxdepth 1  -name "*[sh]d[a-z]"  | sort | awk '{ printf "FALSE""\0"$0"\0" }' | xargs -0 zenity --list --height=400 --width=600 --title="Drive to Install To" --text="Choose a drive" --radiolist --multiple --column ' ' --column 'Devices')
		ANS2=$(zenity  --list --height=400 --width=800 --text "Type Of Installation" --radiolist  --column "Pick" --column "Type" TRUE "Live USB" FALSE "SD Card" FALSE "Windows" FALSE "Manual File Selection")
		case "$ANS2" in
			'Live USB')
				OS=$(zenity  --list --height=400 --width=600 --text "OS for Installation" --radiolist  --column "Pick" --column "Type" TRUE "Linux Mint 18 Mate x32" FALSE "Linux Mint 18 Mate x64" FALSE "CentOS 7" FALSE "CentOS 7 Net" FALSE "Ubuntu 16.04 x32" FALSE "Ubuntu 16.04 x64" FALSE "Debian 8 x32 Net" FALSE "Debian 8 x64 Net" )
				case "$OS" in
					"Linux Mint 18 Mate x32")
						FILE=${mintx32}
						;;
					"Linux Mint 18 Mate x64")
						FILE=${mintx64}
						;;
					"Ubuntu 16.04 x32")
						FILE=${ubuntu1604x32}
						;;
					"Ubuntu 16.04 x64")
						FILE=${ubuntu1604x64}
						;;
					"CentOS 7")
						FILE=${centos7}
						;;
					"CentOS 7 Net")
						FILE=${centos7net}
						;;
					"Debian 8 x32 Net")
						FILE=${debian8x32net}
						;;
					"Debian 8 x64 Net")
						FILE=${mintx32}
						;;
					esac
				;;
			'SD Card')
				OS=$(zenity  --list --height=400 --width=600  --text "OS for Installation" --radiolist  --column "Pick" --column "Type" TRUE "Raspbian" FALSE "Bananian" FALSE "OSMC" FALSE "OpenELEC")
				case "$OS" in
					"Raspbian")
						CHOICE=$(zenity  --list --height=400 --width=600 --text "OS for Installation" --radiolist  --column "Pick" --column "Type" TRUE "Jessie" FALSE "Wheezy")
						case "$CHOICE" in
							"Jessie")
								FILE=${raspbian_jessie}
								;;
							"Wheezy")
								FILE=${raspbian_wheezy}
								;;
						esac
						;;
					"OpenELEC")
						FILE=${openelec}
						;;
					"Bananian")
						FILE=${bananian}
						;;
					"OSMC")
						gksu osmcinstaller
						;;
				esac
				;;
			'Windows')
				OS=$(zenity  --list --height=400 --width=600 --text "OS for Installation" --radiolist  --column "Pick" --column "Type" TRUE "7 x32" FALSE "7 x64" FALSE "10 x32" FALSE "10 x64" FALSE "2012 R2")
				case $OS in 
					"2012 R2")
						FILE=${serverR2}
						;;
					"7 x32")
						FILE=${sevenx32}
						;;
					"7 x64")
						FILE=${sevenx64}
						;;
					"10 x32")
						FILE=${tenx32}
						;;
					"10 x32")
						FILE=${tenx64}
						;;
				esac
				if [ -z "$FILE" ]; then
					zenity --info --text "Windows File not selected."
				else
					sudo mkfs.ntfs -f ${DRIVE}
					sudo dd if=/usr/lib/syslinux/bios/mbr.bin of=${DRIVE}
					sudo mount -o loop ${FILE} /mnt/iso
					sudo mount ${DRIVE}1 /mnt/usb
					cp -r /mnt/iso/* /mnt/usb/
					sync
				fi
					;;
			'Manual File Selection')
				FILE=$(zenity --file-selection --title="Select a File" --filename=$HOME/ISO_Images/)
				;;
		esac
		if [ "$ANS2" != "Windows" ]; then
			if [ -z "$FILE" ]; then
					zenity --info --text "Operating System File not selected"
			else
				zenity --info --text "Writing "${FILE}" to "${DRIVE}
				terminator -T "Writing USB Now" -e "sudo pv "${FILE}" | sudo dd of="${DRIVE}" bs=1M"
				zenity --info --text "Flashing Complete"
			fi
		fi
		;;
	"CD and DVD Disc")
		OS=$(zenity  --list --height=400 --width=600  --text "OS for Installation" --radiolist  --column "Pick" --column "Type" TRUE "Choose File..." FALSE "Plop BootLoader" FALSE "7 x64" FALSE "7 x32" FALSE "10 x32" FALSE "10 x64" FALSE "2012 R2" FALSE "Linux Mint 18 Mate x32" FALSE "Linux Mint 18 Mate x64" FALSE "Ubuntu 16.04 x32" FALSE "Ubuntu 16.04 x64" FALSE "CentOS 7" FALSE "CentOS 7 Netinst" FALSE "Debian 8 x32 Net" FALSE "Debian 8 x64 Net")
		case "$OS" in
			"Choose File...")
				FILE=$(zenity --file-selection --title="Select a File" --filename=$HOME/Downloads/)
				;;
			"Plop BootLoader")
				FILE=${plop}
				;;
			"2012 R2")
				FILE=${serverR2}
				zenity --info --text "Use DL DVD!!"
				;;
			"7 x32")
				FILE=${sevenx32}
				;;
			"7 x64")
				FILE=${sevenx64}
				zenity --info --text "Use DL DVD!!"
				;;
			"10 x32")
				FILE=${tenx32}
				;;
			"10 x64")
				FILE=${tenx64}
				;;	
			"Linux Mint 18 Mate x32")
				FILE=${mintx32}
				;;
			"Linux Mint 18 Mate x64")
				FILE=${mintx64}
				;;
			"Ubuntu 16.04 x32")
				FILE=${ubuntu1604x32}
				;;
			"Ubuntu 16.04 x64")
				FILE=${ubuntu1604x64}
				;;
			"CentOS 7")
				FILE=${centos7}
				;;
			"CentOS 7 Net")
				FILE=${centos7net}
				;;
			"Debian 8 x32 Net")
				FILE=${debian8x32net}
				;;
			"Debian 8 x64 Net")
				FILE=${mintx32}
				;;
			esac
			if [ -z "$FILE" ]; then
				zenity --info --text "Nothing Selected"
			else
				terminator -T "Writing Disc Now" -e "sudo cdrecord -v -dao -eject dev=/dev/sr0 ${FILE}"
				zenity --info --text "Disc Created" 	
			fi
			;;
	esac



