#!/bin/bash

cd /home/iainstott/GitRepo/Scripts

hostname=$(hostname)
server='alienserver'
bladeserver='bladeserver'
kodiHOME='/home/iainstott/.kodi/'
kodiLOCAL='/home/iainstott/Kodi/'
kodiLOCALCURRENT=${kodiLOCAL}"currentBuild/"
kodiREMOTE='/media/Backup/Iains/KodiRepo/'
kodiREMOTECURRENT=${kodiREMOTE}"currentBuild/"
kodiRESET=${kodiLOCAL}"reset.tgz"
kodiCURRENT=${kodiLOCAL}"current.tgz"
kodiArchive=${kodiLOCAL}"backupFolder/BuildArchive/"
IPTVM3U=${kodiLOCAL}"IPTVLists/IPTV.m3u"
IPTVMYM3U=${kodiLOCAL}"IPTVLists/MYIPTV.m3u"
IPTVfile=${kodiLOCAL}"IPTV.m3u"
IPTVMYfile=${kodiLOCAL}"MYIPTV.m3u"
IPTVRadioFolder=${kodiLOCAL}"IPTVLists/Radio/"
IPTVChannelList=${kodiLOCAL}"/IPTVLists/Channels.txt"
updateGUIDE='NO'

one=( '1' 'one' )
two=( '2' 'two' )
three=( '3' 'three')
four=( '4' 'four' )
five=( '5' 'five' )

hd=( 'hd' '720' '1080p' '1080' )

function kodiSORTIPTV_ProcessStart {
	rsync -avP --delete-during /media/NFS/Backup/Iains/KodiRepo/ /home/iainstott/Kodi/
	rm -rf ${kodiLOCAL}"IPTVLists/Archive/${DATE}_1.m3u"
	rm -rf ${kodiLOCAL}"IPTVLists/Archive/${DATE}_2.m3u"
	rm -rf ${IPTVChannelList}
	touch ${IPTVChannelList}
	rm -rf ${IPTVRadioFolder}
	touch ${IPTVRadioFolder}
	rm -rf ${IPTVM3U}
	rm -rf ${IPTVMYM3U}
	touch ${IPTVM3U}
	touch ${IPTVMYM3U}
	n=1
	DATE=$(date +%d-%m-%y)
	wget -O ${kodiLOCAL}"IPTVLists/Archive/${DATE}_1.m3u" "http://uk-mega-iptv.is-found.org:25461/get.php?username=IainStott&password=QAcEiPTJsK&type=m3u&output=ts"
	}

function kodiSORTIPTV_ProcessEnd {
	python3 ./lib/python/kodiSORTIPTV_GUI.py
	cp ${IPTVM3U} ${kodiLOCAL}"IPTV.m3u"
	cp ${IPTVMYM3U} ${kodiLOCAL}"MYIPTV.m3u"
	if [ ${updateGUIDE} == 'YES' ]
	then
		/usr/bin/mono ${kodiLOCAL}"WebGrab/WebGrab+Plus.exe" ${kodiLOCAL}"WebGrab/"
		/usr/bin/mono ${kodiLOCAL}"WebGrab/WebGrab+Plus.exe" ${kodiLOCAL}"MegaWEBGRAB/"
		cp ${kodiLOCAL}"IPTVLists/guide.xml" ${kodiLOCAL}"guide.xml"
		cp ${kodiLOCAL}"MegaWEBGRAB/guide.xml" ${kodiLOCAL}"megaguide.xml"
	fi
	if [ ${hostname} == ${server} ] || [ ${hostname} == ${bladeserver} ]
	then
		rsync -azvP --delete-during /home/iainstott/Kodi/ /media/NFS/Backup/Iains/KodiRepo/
	fi
}


function kodiSORTIPTV_Process {
	kodiSORTIPTV_ProcessStart
	updateGUIDE='YES'
	python3 -c 'import lib.python.kodiSORTIPTV_GUI as sortiptv; sortiptv.renumberCHANNELS()'
	kodiSORTIPTV_ProcessEnd
}

function kodiSORTIPTV_GUI {
	GUI_START='YES'
	kodiSORTIPTV_ProcessStart
	zenity --question --text="Re-Number Channels" --ok-label="Yes" --cancel-label="No"
	if [ $? = 0 ] ; then
		python3 -c 'import lib.python.kodiSORTIPTV_GUI as sortiptv; sortiptv.renumberCHANNELS()'
	else
		updateGUIDE='NO'
	fi
	zenity --question --text="Update Guide" --ok-label="Yes" --cancel-label="No"
	if [ $? = 0 ] ; then
		updateGUIDE='YES'
	else
		updateGUIDE='NO'
	fi
	kodiSORTIPTV_ProcessEnd
}
