#!/bin/bash

hostname=$(hostname)
server='physical-server'
kodiHOME='/home/iainstott/.kodi/'
kodiLOCAL='/home/iainstott/Kodi/'
kodiLOCALCURRENT=${kodiLOCAL}"currentBuild/"
kodiREMOTE='/mnt/Backup_Drive/BackupFolder/Backup/Iains/KodiRepo/'
kodiREMOTECURRENT=${kodiREMOTE}"currentBuild/"
kodiRESET=${kodiLOCAL}"reset.tgz"
kodiCURRENT=${kodiLOCAL}"current.tgz"
kodiArchive=${kodiLOCAL}"backupFolder/BuildArchive/"
IPTVM3U=${kodiLOCAL}"IPTVLists/IPTV.m3u"
IPTVMYM3U=${kodiLOCAL}"IPTVLists/MYIPTV.m3u"
IPTVfile=${kodiLOCAL}"IPTV.m3u"
IPTVtempfile=${kodiLOCAL}"IPTVtemp.m3u"
IPTVChannelFolder=${kodiLOCAL}"IPTVLists/Channels/"
IPTVChannelList=${kodiLOCAL}"/IPTVLists/Channels.txt"

rm -rf ${IPTVChannelList}
touch ${IPTVChannelList}
rm -rf ${IPTVChannelFolder}
mkdir ${IPTVChannelFolder}
rm -rf ${IPTVM3U}
rm -rf ${IPTVMYM3U}
touch ${IPTVM3U}
touch ${IPTVMYM3U}
rm -rf ${kodiLOCAL}IPTVLists/strings.txt
touch ${kodiLOCAL}IPTVLists/strings.txt

n=001

DATE=$(date +%d-%m-%y)
wget -O ${kodiLOCAL}"IPTVLists/Archive/${DATE}_1.m3u" "http://uk-mega-iptv.is-found.org:25461/get.php?username=IainStott&password=QAcEiPTJsK&type=m3u&output=ts"
wget -O ${kodiLOCAL}"IPTVLists/Archive/${DATE}_2.m3u" "http://uk-mega-iptv.is-found.org:25461/get.php?username=IainStott2&password=QAcEiPTJsK&type=m3u&output=ts"
cp ${kodiLOCAL}"IPTVLists/Archive/${DATE}_1.m3u" ${IPTVtempfile}
head -n 1 ${IPTVtempfile} > /dev/null && sed -i '1,+2d' ${IPTVtempfile}
while [ -f ${IPTVtempfile} ]; do
	firstLINE=$(head -n 1 ${IPTVtempfile})
	if [ ${#firstLINE} -ge 1 ]
	then
		name=${firstLINE##*,}
		name=${name##*|}
		echo $name >> ${kodiLOCAL}/IPTVLists/Channels.txt
		name=${name//[^[:alnum:]]/_}
		number=$(echo $n | awk '{printf("%04d", $1)}')
		head -2 ${IPTVtempfile} > ${IPTVChannelFolder}${number}"_"${name}".m3u" && sed -i '1,+1d' ${IPTVtempfile}
		((n++))
	else
		rm -rf ${IPTVtempfile} 
	fi
done

channels=`cd ${IPTVChannelFolder}
		 find ./ -name "*.*" -type f | sort -z |\
         zenity --list --checklist --height=800 --width=600 --separator='\n' --title="Select Results." \
                --text="Finding all Channels..." --column="" --column="Files"`

