#!/bin/bash

cd /home/iainstott/GitRepo/Scripts

hostname=$(hostname)
server='physical-server'
bladeserver='bladeserver'
kodiHOME='/home/iainstott/.kodi/'
kodiLOCAL='/home/iainstott/Kodi/'
kodiLOCALCURRENT=${kodiLOCAL}"currentBuild/"
kodiREMOTE='/media/Backup/Iains/KodiRepo/'
kodiREMOTECURRENT=${kodiREMOTE}"currentBuild/"
kodiRESET=${kodiLOCAL}"reset.tgz"
kodiCURRENT=${kodiLOCAL}"current.tgz"
kodiArchive=${kodiLOCAL}"backupFolder/BuildArchive/"
IPTVM3U=${kodiLOCAL}"IPTVLists/IPTV.m3u"
IPTVMYM3U=${kodiLOCAL}"IPTVLists/MYIPTV.m3u"
IPTVfile=${kodiLOCAL}"IPTV.m3u"
IPTVtempfile=${kodiLOCAL}"IPTVtemp.m3u"
IPTVChannelFolder=${kodiLOCAL}"IPTVLists/Channels/"
IPTVChannelList=${kodiLOCAL}"/IPTVLists/Channels.txt"
updateGUIDE='NO'

one=( '1' 'one' )
two=( '2' 'two' )
three=( '3' 'three')
four=( '4' 'four' )
five=( '5' 'five' )

hd=( 'hd' '720' '1080p' '1080' )

function kodiSORTIPTV_ProcessStart {
	if [ ${hostname} == ${server} ] || [ ${hostname} == ${bladeserver} ]
	then
		kodiREMOTE='/media/Backup_NET/Iains/KodiRepo/'
		sudo rsync -avP iainstott@192.168.0.4:/mnt/Backup/Iains/KodiRepo/ /home/iainstott/Kodi/
	fi
	rm -rf ${kodiLOCAL}"IPTVLists/Archive/${DATE}_1.m3u"
	rm -rf ${kodiLOCAL}"IPTVLists/Archive/${DATE}_2.m3u"
	rm -rf ${IPTVChannelList}
	touch ${IPTVChannelList}
	rm -rf ${IPTVChannelFolder}
	mkdir ${IPTVChannelFolder}
	rm -rf ${IPTVM3U}
	rm -rf ${IPTVMYM3U}
	touch ${IPTVM3U}
	touch ${IPTVMYM3U}
	rm -rf ${kodiLOCAL}IPTVLists/strings.txt
	touch ${kodiLOCAL}IPTVLists/strings.txt
	n=1
	DATE=$(date +%d-%m-%y)
	wget -O ${kodiLOCAL}"IPTVLists/Archive/${DATE}_1.m3u" "http://uk-mega-iptv.is-found.org:25461/get.php?username=IainStott&password=QAcEiPTJsK&type=m3u&output=ts"
	cp ${kodiLOCAL}"IPTVLists/Archive/${DATE}_1.m3u" ${IPTVtempfile}
}

function kodiSORTIPTV_ProcessEnd {
	if [ $GUI_START == 'YES' ]
	then
		python3 ./lib/python/kodiSORTIPTV_GUI.py
	else
		python3 ./lib/python/kodiSORTIPTV.py
	fi
	cp ${IPTVM3U} ${kodiLOCAL}"IPTV.m3u"
	cp ${IPTVMYM3U} ${kodiLOCAL}"MYIPTV.m3u"
	if [ ${updateGUIDE} == 'YES' ]
	then
		/usr/bin/mono ${kodiLOCAL}"WebGrab/WebGrab+Plus.exe" ${kodiLOCAL}"WebGrab/"
	fi
	if [ ${hostname} == ${server} ] || [ ${hostname} == ${bladeserver} ]
	then
		rsync -azvP /home/iainstott/Kodi/ iainstott@192.168.1.1:/mnt/Backup/Iains/KodiRepo/
	fi
}

function kodiSORTIPTV_Process {
	kodiSORTIPTV_ProcessStart
	updateGUIDE='YES'
	kodiSORTIPTV_ProcessEnd
}

function kodiSORTIPTV_GUI {
	GUI_START='YES'
	kodiSORTIPTV_ProcessStart
	#channels=`cat ${kodiLOCAL}/IPTVLists/Channels.txt | awk '{print "FALSE\n"$0}' | zenity --list --checklist \
    #     --separator='/ ' --title="Select Results." --height=600 --width=600 \
    #     --text="Finding all channels..." --column="" --column="Select" & zenity --list --checklist \
    #     --separator='/ ' --title="Channels" --height=600 --width=600 \
    #     --text="Channel List" --column="" --column="Select"`
    zenity --question --text="Update Guide" --ok-label="Yes" --cancel-label="No"
	if [ $? = 0 ] ; then
		updateGUIDE='YES'
	else
		updateGUIDE='NO'
	fi
	kodiSORTIPTV_ProcessEnd
}
