#!/bin/bash

raspi1=("192.168.0.4" "Raspi-1" "iainstott") 
raspi2=("192.168.1.2" "Raspi-2" "osmc")
raspi3=("192.168.1.3" "Raspi-3" "root")
raspi4=("192.168.1.4" "Raspi-4" "root")
raspi6=("192.168.0.130" "Raspi-6" "root")
raspi7=("192.168.0.131" "Raspi-7" "root")
server1=("192.168.0.2" "Server-1" "root")
server2=("192.168.0.5" "Server-2" "root")
